# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fpgaol2.xdc

# IP: ip/dist_mem_text/dist_mem_text.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_text || ORIG_REF_NAME==dist_mem_text} -quiet] -quiet
