# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bill/Source/Vivado_Projects/Principle_Of_Computer_Composition/lab5/Pipeline_CPU/Pipeline_CPU.srcs/constrs_1/new/fpgaol2.xdc

# IP: ip/dist_mem_data/dist_mem_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_data || ORIG_REF_NAME==dist_mem_data} -quiet] -quiet

# IP: ip/dist_mem_inst/dist_mem_inst.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_inst || ORIG_REF_NAME==dist_mem_inst} -quiet] -quiet
