# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab4/Single_Cycle_CPU_fib/Single_Cycle_CPU_fib.srcs/sources_1/ip/dist_mem_data/dist_mem_data.xci
# IP: The module: 'dist_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab4/Single_Cycle_CPU_fib/Single_Cycle_CPU_fib.gen/sources_1/ip/dist_mem_data/dist_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab4/Single_Cycle_CPU_fib/Single_Cycle_CPU_fib.srcs/sources_1/ip/dist_mem_data/dist_mem_data.xci
# IP: The module: 'dist_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab4/Single_Cycle_CPU_fib/Single_Cycle_CPU_fib.gen/sources_1/ip/dist_mem_data/dist_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
