# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/18213/Sources/COD_Lab/lab6/Fib_Test/Fib_Test.srcs/sources_1/ip/dist_mem_data/dist_mem_data.xci
# IP: The module: 'dist_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/COD_Lab/lab6/Fib_Test/Fib_Test.gen/sources_1/ip/dist_mem_data/dist_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/18213/Sources/COD_Lab/lab6/Fib_Test/Fib_Test.srcs/sources_1/ip/dist_mem_data/dist_mem_data.xci
# IP: The module: 'dist_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/COD_Lab/lab6/Fib_Test/Fib_Test.gen/sources_1/ip/dist_mem_data/dist_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
