# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab2/lab2.2.1/lab2.2.1.srcs/sources_1/ip/blk_mem_no/blk_mem_no.xci
# IP: The module: 'blk_mem_no' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab2/lab2.2.1/lab2.2.1.gen/sources_1/ip/blk_mem_no/blk_mem_no_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_no'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab2/lab2.2.1/lab2.2.1.srcs/sources_1/ip/blk_mem_no/blk_mem_no.xci
# IP: The module: 'blk_mem_no' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18213/Sources/Vivado_Projects/Principle_Of_Computer_Composition/lab2/lab2.2.1/lab2.2.1.gen/sources_1/ip/blk_mem_no/blk_mem_no_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_no'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
